#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $DINANATH_REPO == "DINANATHBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $DINANATH_REPO == "DINANATHBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $DINANATH_REPO =~ $regex ]]
    then
        if [[ $DINANATH_REPO_BRANCH ]]
        then
            echo "${DINANATH_REPO}/archive/${LEGEND_REPO_BRANCH}.zip"
        else
            echo "${DINANATH_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0xFR0VORC1PUy9MRUdFTkRVU0VSQk9UL2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="DINANATHBOT.zip"
    echo "  ⚜Downloading DinanathBot V5.0Source Code...❤"
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    LEGENDPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  DINANATH V5.0 Cleaning.."
    rm -rf "$zippath"
    sleep 5
    cd $DINANATHPATH
    echo "    • Starting Lêɠêɳ̃dDINANATG 5.0•    "
    echo "
    DINANATHBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
